language: c
sudo: false

branches:
  only:
    - master
    - Circle-CI-Support

cache: apt

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - gcc-5
    - gcc-6
    - libnss3-dev
    - libtool

env:
  - MATRIX_EVAL="true"

matrix:
  include:
  - os: linux
    compiler: clang
  - os: linux
    compiler: gcc-4.8
  - os: linux
    compiler: gcc-5
  - os: linux
    compiler: gcc-6
  - os: osx
    compiler: clang
    osx_image: xcode6.2
  - os: osx
    compiler: clang
    osx_image: xcode7.3
  - os: osx
    compiler: clang
    osx_image: xcode8
  - os: osx
    compiler: gcc-6
    env:
      - MATRIX_EVAL="brew install gcc6 && CC=gcc-6 && CXX=g++-6"
    osx_image: xcode8
  - os: osx
    compiler: clang
    osx_image: xcode9

before_install:
  - if [ $TRAVIS_OS_NAME == osx ] ; then
       eval "${MATRIX_EVAL}" ;
       brew uninstall libtool ;
       brew install nss openssl automake autoconf libtool $INSTALL || true ;
    fi

before_script:
  - $CC --version

script:
  - autoreconf -i
  - if [ $TRAVIS_OS_NAME == osx ] ; then ./configure --with-openssl=/usr/local/Cellar/openssl/* ; fi
  - if [ $TRAVIS_OS_NAME == linux ] ; then ./configure ; fi
  - make V=1
  - make test

after_script:
  - make test-clean
