language: c
sudo: false

branches:
  only:
    - master

cache: apt

matrix:
  include:
  - os: linux
    compiler: clang
    addons:
      apt:
        packages: [ "libnss3-dev", "libtool" ]
        sources: &sources
          - ubuntu-toolchain-r-test
          - llvm-toolchain-precise
  - os: linux
    compiler: clang-3.8
    addons:
      apt:
        packages: ["clang-3.8", "libnss3-dev", "libtool" ]
        sources: *sources
  - os: linux
    compiler: gcc-5
    addons:
      apt:
        packages: ["gcc-5", "libnss3-dev", "libtool" ]
        sources: *sources
  - os: osx
    compiler: clang
    osx_image: xcode6.1
  - os: osx
    compiler: clang
    osx_image: xcode7.2
  - os: osx
    env: INSTALL=gcc
    compiler: gcc-4.9

before_install:
  - if [ $TRAVIS_OS_NAME == osx -a $INSTALL == gcc ] ; then brew update ; fi
  - if [ $TRAVIS_OS_NAME == osx ] ; then brew install nss openssl $INSTALL || true ; fi

script:
  - autoreconf -i
  - if [ $TRAVIS_OS_NAME == osx ] ; then ./configure --with-openssl=/usr/local/Cellar/openssl/* ; fi
  - if [ $TRAVIS_OS_NAME == linux ] ; then ./configure ; fi
  - make V=1
  - make test
