language: c

compiler:
  - gcc-4.8
  - gcc-4.9
  - gcc-5.0
  - clang-3.6
  - clang-3.7
  - clang-3.8

os:
  - linux
  - osx

install:
  - if [ $TRAVIS_OS_NAME == linux ] ; then sudo apt-get update -qq ; sudo apt-get install -y libssl-dev libnss3 libnss3-dev build-essential automake autoconf gcc-4.8 gcc-4.9 gcc-5 clang-3.6 clang-3.7 clang-3.8 ; fi
  - if [ $TRAVIS_OS_NAME == osx ] ; then brew install nss openssl automake autoconf gcc-4.8 gcc-4.9 gcc-5 clang-3.6 clang-3.7 clang-3.8 ; fi

before_script: autoreconf -i
