language: c

compiler:
  - gcc
  - clang

os:
  - linux
  - osx

install:
  - if [ $TRAVIS_OS_NAME == linux ] ; then sudo apt-get install -y -qq libssl-dev build-essential automake autoconf ; fi
  - if [ $TRAVIS_OS_NAME == osx ] ; then brew install nss ; fi

before_script: autoreconf -i
