language: c
sudo: false

branches:
  only:
    - master

cache: apt

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - gcc-5
    - gcc-6
    - libnss3-dev
    - libtool

matrix:
  include:
  - os: linux
    compiler: clang
  - os: linux
    compiler: gcc-4.8
  - os: linux
    compiler: gcc-5
  - os: linux
    compiler: gcc-6
  - os: osx
    compiler: clang
    osx_image: xcode6.1
  - os: osx
    compiler: clang
    osx_image: xcode7.2
  - os: osx
    compiler: clang
    osx_image: xcode8
  - os: osx
    env: INSTALL=gcc
    compiler: gcc-4.9
    osx_image: xcode8

before_install:
  - if [ $TRAVIS_OS_NAME == osx ] ; then
       brew uninstall libtool ;
       brew install nss openssl automake autoconf libtool $INSTALL || true ;
    fi

script:
  - autoreconf -i
  - if [ $TRAVIS_OS_NAME == osx ] ; then ./configure --with-openssl=/usr/local/Cellar/openssl/* ; fi
  - if [ $TRAVIS_OS_NAME == linux ] ; then ./configure ; fi
  - make V=1
  - make test
  - make test-clean
