version: 1.0.{build}
shallow_clone: true

branches:
  only:
    - master

os: Windows Server 2012 R2

platform:
  - x86
  - x64

configuration:
  - Release
  - Debug

environment:
  global:
    MSYS_ROOT: C:/MinGW/msys/1.0

build:
    verbosity: detailed

init:
    - 'echo Building libevent %version% for Windows'
    - 'echo System architecture: %PLATFORM%'
    - 'echo Repo build branch is: %APPVEYOR_REPO_BRANCH%'
    - 'echo Build folder is: %APPVEYOR_BUILD_FOLDER%'

install:
    - set PATH=C:\cygwin\bin;%PATH%;C:\MinGW\msys\1.0\bin;C:\MinGW\bin
    - set CYG_ROOT=C:/MinGW/msys/1.0
    - set OPENSSL_VERSION=1_0_2d
    - ps: >-
        If ($env:Platform -Match "x86") {
            $env:OPENSSL_PLATFORM="Win32"
        } Else {
            $env:OPENSSL_PLATFORM="Win64"
        }
        Start-FileDownload https://slproweb.com/download/Win32OpenSSL-${env:OPENSSL_VERSION}.exe -FileName C:\WinOpenSSL.exe
    - C:\WinOpenSSL.exe /SILENT /VERYSILENT /SP- /SUPPRESSMSGBOXES /NORESTART

build_script:
    - cmd: 'echo Cygwin root is: %CYG_ROOT%'
    - cmd: 'echo Build folder is: %APPVEYOR_BUILD_FOLDER%'
    - cmd: 'echo Repo build branch is: %APPVEYOR_REPO_BRANCH%'
    - cmd: 'echo Repo build commit is: %APPVEYOR_REPO_COMMIT%'
    - cmd: 'echo "C:\MinGW /mingw" >%CYG_ROOT%/etc/fstab'
    - cmd: 'C:\MinGW\bin\mingw-get install autotools autoconf automake libtool'
    - cmd: 'echo Autogen running...'
    - cmd: '%CYG_ROOT%/bin/bash -lc "cd $APPVEYOR_BUILD_FOLDER; mount C:/MinGW /mingw"'
    - cmd: '%CYG_ROOT%/bin/bash -lc "cd $APPVEYOR_BUILD_FOLDER; autoreconf -i"'
    - cmd: '%CYG_ROOT%/bin/bash -lc "cd $APPVEYOR_BUILD_FOLDER; ./configure"'
    - cmd: '%CYG_ROOT%/bin/bash -lc "cd $APPVEYOR_BUILD_FOLDER; make"'

cache:
  - C:\OpenSSL-Win32
  - C:\OpenSSL-Win64

