version: 1.0.{build}
shallow_clone: true

branches:
  only:
    - master

skip_tags: true

os: Windows Server 2012 R2

platform:
  - x86

# Add x64 platform later
#  - x64

configuration:
  - Release

# Add debug configuration later
#  - Debug

environment:
  global:
    MSYS_ROOT: C:/MinGW/msys/1.0

build:
    verbosity: detailed

init:
    - git config --global core.autocrlf input
    - 'echo Building version %version% for Windows'
    - 'echo System architecture: %PLATFORM%'
    - 'echo Repo build branch is: %APPVEYOR_REPO_BRANCH%'
    - 'echo Build folder is: %APPVEYOR_BUILD_FOLDER%'

install:
    - set PATH=C:\cygwin\bin;%PATH%;C:\MinGW\msys\1.0\bin;C:\MinGW\bin
    - set CYG_ROOT=C:/MinGW/msys/1.0
    - set OPENSSL_VERSION=1_0_2d

# Re-add OpenSSL support later
#     - ps: >-
#         If ($env:Platform -Match "x86") {
#             $env:OPENSSL_PLATFORM="Win32"
#         } Else {
#             $env:OPENSSL_PLATFORM="Win64"
#         }
#         Start-FileDownload https://slproweb.com/download/Win32OpenSSL-${env:OPENSSL_VERSION}.exe -FileName C:\WinOpenSSL.exe
#     - C:\WinOpenSSL.exe /SILENT /VERYSILENT /SP- /SUPPRESSMSGBOXES /NORESTART

build_script:
    - cmd: if %PLATFORM%==x86 SET OPENSSL_PLATFORM=Win32
    - cmd: if %PLATFORM%==x64 SET OPENSSL_PLATFORM=Win64
    - cmd: 'echo Cygwin root is: %CYG_ROOT%'
    - cmd: 'echo Build folder is: %APPVEYOR_BUILD_FOLDER%'
    - cmd: 'echo Repo build branch is: %APPVEYOR_REPO_BRANCH%'
    - cmd: 'echo Repo build commit is: %APPVEYOR_REPO_COMMIT%'
    - cmd: 'echo OpenSSL Platform is: %OPENSSL_PLATFORM%'
    - cmd: 'echo "C:\MinGW /mingw" >%CYG_ROOT%/etc/fstab'
    - cmd: 'C:\MinGW\bin\mingw-get install autotools autoconf automake libtool'
    - cmd: 'echo Autogen running...'
    - cmd: '%CYG_ROOT%/bin/bash -lc "cd $APPVEYOR_BUILD_FOLDER; mount C:/MinGW /mingw"'
    - cmd: '%CYG_ROOT%/bin/bash -lc "cd $APPVEYOR_BUILD_FOLDER; autoreconf -i"'
    - cmd: '%CYG_ROOT%/bin/bash -lc "cd $APPVEYOR_BUILD_FOLDER; CFLAGS=\"-D_GNU_SOURCE -Doff_t=_off_t -Doff64_t=_off64_t\" ./configure"'

    - cmd: '%CYG_ROOT%/bin/bash -lc "cd $APPVEYOR_BUILD_FOLDER; make V=1"'

# Re-add OpenSSL later
#     - cmd: '%CYG_ROOT%/bin/bash -lc "cd $APPVEYOR_BUILD_FOLDER; CFLAGS=\"-D_GNU_SOURCE\" ./configure --with-openssl=C:/OpenSSL-%OPENSSL_PLATFORM%"'

# cache:
#   - C:\OpenSSL-Win32
#   - C:\OpenSSL-Win64

